version: '3'

services:
  reverse-proxy:
    image: traefik:v2.1
    hostname: project.lambla.eu
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - conf:/etc/traefik/
      - /home/dreaser/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.project.lambla.eu`)"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"
        - "traefik.docker.network=traefik_traefik"
    networks:
      - traefik
volumes:
  conf:
    driver: local
    driver_opts:
      type: none
      device: /home/dreaser/traefik/config/
      o: bind

networks:
  traefik:
    driver: overlay
    external: false  

